// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBoIpoC5-Yggf2kAu13pSe8f4XJXa_t8g',
    appId: '1:747384689964:web:a25d7c1cd7a9c5c1af0889',
    messagingSenderId: '747384689964',
    projectId: 'edutivflutter',
    authDomain: 'edutivflutter.firebaseapp.com',
    storageBucket: 'edutivflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Q1iP2dx7LzZ1t6P60NbcVZcBy_p7PeM',
    appId: '1:747384689964:android:725ad9fddda70181af0889',
    messagingSenderId: '747384689964',
    projectId: 'edutivflutter',
    storageBucket: 'edutivflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw4b0k1w201dkgagASdW68sziBqVHmv_U',
    appId: '1:747384689964:ios:921ec4401ff66f39af0889',
    messagingSenderId: '747384689964',
    projectId: 'edutivflutter',
    storageBucket: 'edutivflutter.firebasestorage.app',
    iosBundleId: 'com.example.digitalLearningApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw4b0k1w201dkgagASdW68sziBqVHmv_U',
    appId: '1:747384689964:ios:921ec4401ff66f39af0889',
    messagingSenderId: '747384689964',
    projectId: 'edutivflutter',
    storageBucket: 'edutivflutter.firebasestorage.app',
    iosBundleId: 'com.example.digitalLearningApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBoIpoC5-Yggf2kAu13pSe8f4XJXa_t8g',
    appId: '1:747384689964:web:67acdd677723dfd6af0889',
    messagingSenderId: '747384689964',
    projectId: 'edutivflutter',
    authDomain: 'edutivflutter.firebaseapp.com',
    storageBucket: 'edutivflutter.firebasestorage.app',
  );
}
